### ISSUE TITLE
New files listing

### ISSUE THREAD

**Issue by shighfield** [MagickaBBS/MagickaBBS#10]
When there are new files it just shows you the areas, then you need to change to the area and select (L)ist files by (U)pload date.  Anyway to just show the new files?

**Comment by apamment** [comment]
Hmm, do you think I should do a "new" new file scan like the "new" email scan and mimic how ezycom does new file scans, or leave it the way it is and add an option when doing a listing to show only new files?

**Comment by shighfield** [comment]
Either way works.  The second method would work more in line with the rest of the package

**Comment by apamment** [comment]
Should be done now, modified magicka.strings and added a new files only option under file listings.. will reopen if you have issues
