### ISSUE TITLE
Read to List mode

### ISSUE THREAD

**Issue by shighfield** [MagickaBBS/MagickaBBS#15]
What about a key that would let me jump from read mode to list mode?  ie: I'm (R)eading (N)ew messages in an area that still gets a massive amount of traffic, and after  a few I realize I'm bored of this thread and want to jump back to List mode to skip it.

**Comment by apamment** [comment]
I don't think I've ever used read mode, I added it at Paul's request. I always go list messages -> new and select where i want to start, then if you want to skip press q and it takes you back to list mode.

**Comment by shighfield** [comment]
Yeah... I'm a dumb ass.  Just gonna change the (R)ead mode to list mode.
