### ISSUE TITLE
Magichat not working properly with plain Linux command line telnet program

### ISSUE THREAD

**Issue by ufud-org** [MagickaBBS/MagickaBBS#19]
When using the Linux telnet program (in xterm), Magichat (built-in text client) only shows the first message entered by a user, then refuses to accept any input, including the /Quit command. Below I pasted an example of what happens:

(Magicka)[lodger]: howdy
(Magicka)[lodger]: [K
(Magicka)[lodger]: [K
(Magicka)[lodger]: [K

**Comment by apamment** [comment]
Thanks for the bug report !

I've fixed this now in v0.9-patch and v0.10-alpha

I was not taking into account in the chat that some clients use \r\0 instead of \r\n at the end of a line.
